<?php
namespace API;

// Common constants to use within your API script
const ERROR_AUTHENTICATION_FAILURE = 1;
const ERROR_TERMINAL_NOT_FOUND = 2;
const ERROR_TERMINALDATAMINUTELY_NOT_FOUND = 3;
const ERROR_INPUT_VALIDATION_REQUIRED_PASSWORD = 4;
const ERROR_USER_NOT_FOUND = 5;
const ERROR_ACCESS_DENIED = 6;
const ERROR_INPUT_VALIDATION_PASSWORD_CONFIRM = 7;
const ERROR_NO_MATCH = 8;
const ERROR_INPUT_VALIDATION_REQUIRED_FCMIDENTIFIER = 9;
const ERROR_INPUT_VALIDATION_REQUIRED_USER_ID = 10;
const ERROR_INPUT_VALIDATION_REQUIRED_SUPPORTREQUESTRESPONSETIMEFROM = 11;
const ERROR_INPUT_VALIDATION_REQUIRED_SUPPORTREQUESTRESPONSEMESSAGE = 12;
const ERROR_INVALID_JSON = 13;
const ERROR_API_FAIL = 14;
const ERROR_INPUT_VALIDATION_REQUIRED_MESSAGE_TIME_FROM = 15;

const ERROR_VALIDATION_REQUIRED = 16;
?>